#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Takuya Nagamine <s21c1090ke@s.chibakoudai.jp>
# SPDX-License-Identifier: BSD-3-Clause
import sys
ans = 0
for line in sys.stdin:
    try: 
        ans -= int(line)
    except:
        ans -= float(line)

print(ans)
